# Generated by Django 2.1.5 on 2021-10-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='des',
            field=models.TextField(default=''),
        ),
    ]
