# Generated by Django 2.1.5 on 2021-12-22 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='phn',
            new_name='phone',
        ),
    ]
