# Generated by Django 2.1.5 on 2021-12-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20211222_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='confirmpassword',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
