# Generated by Django 2.1.5 on 2021-12-27 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='table',
            new_name='Tablebook',
        ),
    ]
