# Generated by Django 2.1.5 on 2021-12-27 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20211227_1304'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tablebook',
            new_name='Tablebooking',
        ),
    ]
