# Generated by Django 2.1.5 on 2021-12-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20211227_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookingdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
    ]
