# Generated by Django 2.1.5 on 2021-12-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20211227_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdate',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
