# Generated by Django 2.1.5 on 2021-12-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20211227_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table_Booked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingtime', models.IntegerField(default='')),
            ],
        ),
    ]
