# Generated by Django 2.1.5 on 2021-12-28 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_table_booked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table_Booked',
        ),
    ]
