# Generated by Django 2.1.5 on 2021-12-28 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_delete_table_booked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingdate',
            old_name='date',
            new_name='bookingdate_time',
        ),
    ]
