# Generated by Django 2.1.5 on 2021-12-28 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20211228_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingdate',
            old_name='bookingdate_time',
            new_name='date',
        ),
    ]
