# Generated by Django 2.1.5 on 2022-01-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_auto_20211230_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
