# Generated by Django 2.1.5 on 2022-01-05 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
