# Generated by Django 2.1.5 on 2022-01-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_auto_20220105_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='images',
            field=models.ImageField(blank=True, default='', upload_to='pro_img'),
        ),
    ]
